---
# For detailed instructions on using this file, visit:
# https://aka.ms/alz/accelerator/docs

# Basic Inputs
iac_type: "terraform"
bootstrap_module_name: "alz_local"
starter_module_name: "platform_landing_zone"

# Shared Interface Inputs
bootstrap_location: "westus2"
starter_locations: ["eastus2","westus2"]
root_parent_management_group_id: ""
subscription_id_management: "8504c123-c9b5-4a0a-acd9-e5162d77a559"
subscription_id_identity: "aeff45a4-109b-45c7-bb9a-7e02fac8110e"
subscription_id_connectivity: "de311b7b-392e-438e-863d-235abc9c1cf1"

# Bootstrap Inputs
target_directory: ""
create_bootstrap_resources_in_azure: false
bootstrap_subscription_id: "8504c123-c9b5-4a0a-acd9-e5162d77a559"
service_name: "ned"
environment_name: "mgmt"
postfix_number: 1
grant_permissions_to_current_user: true

# Advanced Inputs
bootstrap_module_version: "latest"
starter_module_version: "latest"
#output_folder_path: "/accelerator/output"